# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=20)),
                ('sigla', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=20)),
                ('ano', models.CharField(max_length=20)),
                ('logo', models.CharField(max_length=20)),
                ('data_de_inicio', models.DateField(blank=True, null=True)),
                ('data_de_fim', models.DateField(blank=True, null=True)),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to='eventos.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_inscricao', models.DateField(blank=True, null=True)),
                ('preco', models.FloatField()),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eventos.Pessoa')),
                ('cpf', models.CharField(max_length=20)),
                ('mae', models.CharField(max_length=150)),
                ('pai', models.CharField(max_length=150)),
            ],
            bases=('eventos.pessoa',),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.PessoaFisica'),
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.PessoaFisica'),
        ),
    ]
